version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27018

  mongo:
    image: mongo
    ports:
      - "27018:27018"